### ISSUE TITLE
Topic idea: Book review of "What Money Can't Buy: The Moral Limits of Markets" by Michael J. Sandel

### ISSUE THREAD

**Issue by taylor** [vulk/Austin_Software_Co-operatives#24]
What Money Can't Buy:  The Moral Limits of Markets
By: Michael J. Sandel

## Publisher's Summary

> Should we pay children to read books or to get good grades? Should we allow corporations to pay for the right to pollute the atmosphere? Is it ethical to pay people to test risky new drugs or to donate their organs? What about hiring mercenaries to fight our wars? Auctioning admission to elite universities? Selling citizenship to immigrants willing to pay? In What Money Can’t Buy, Michael J. Sandel takes on one of the biggest ethical questions of our time: Is there something wrong with a world in which everything is for sale? If so, how can we prevent market values from reaching into spheres of life where they don’t belong? What are the moral limits of markets? In recent decades, market values have crowded out nonmarket norms in almost every aspect of life—medicine, education, government, law, art, sports, even family life and personal relations. Without quite realizing it, Sandel argues, we have drifted from having a market economy to being a market society. Is this where we want to be?
> 
> In his New York Times best seller Justice, Sandel showed himself to be a master at illuminating, with clarity and verve, the hard moral questions we confront in our everyday lives. Now, in What Money Can’t Buy, he provokes an essential discussion that we, in our marketdriven age, need to have: What is the proper role of markets in a democratic society—and how can we protect the moral and civic goods that markets don’t honor and that money can’t buy?
>
> ©2012 Michael J. Sandel (P)2012 Macmillan Audio

goodreads: https://www.goodreads.com/book/show/13221379-what-money-can-t-buy
audible: https://www.audible.com/pd/What-Money-Cant-Buy-Audiobook/B007RPQT6A

**Comment by lixuna** [comment]
Completed Oct 2020
