### ISSUE TITLE
The tyranny of merit by Michael sandel

### ISSUE THREAD

**Issue by ashleighgregory** [vulk/Austin_Software_Co-operatives#28]

**Comment by lixuna** [comment]
Completed on Dec 2, 2020 

Slides https://docs.google.com/presentation/d/1h9bwlcfGQXfVVEFX98F-WaDxtqxzI520FDHXH0eOTTc/edit#slide=id.p

Mindmap https://www.mindomo.com/mindmap/0b0797c1f1844d7ba3279b13e1a8e26e

**Comment by taylor** [comment]
https://www.youtube.com/watch?v=Qewckuxa9hw
The tyranny of merit | Michael Sandel
Sep 15, 2020

**Comment by taylor** [comment]
https://www.youtube.com/watch?v=dRolGQ3QJPE
RSA Minimate: The Tyranny of Merit | Michael Sandel
