### ISSUE TITLE
Topic idea: The Democratic Worker-Owned Firm - David Ellerman

### ISSUE THREAD

**Issue by lixuna** [vulk/Austin_Software_Co-operatives#29]
## Reading Material:  The Democratic Worker-Owned Firm by David Ellerman

- Paperback, 236 pages
- Published by Routledge

Paperback versions available on:
- Amazon
- [Good Reads](https://www.goodreads.com/book/show/31160646-the-democratic-worker-owned-firm)
- Routledge Publishers

**Comment by taylor** [comment]
http://www.ellerman.org/wp-content/uploads/2018/04/Ellerman.-1990.-The-Democratic-Worker-Owned-Firm-1.pdf

**Comment by taylor** [comment]
Word doc version https://ellerman.org/Davids-Stuff/Books/demofirm.doc

**Comment by taylor** [comment]
Slides for meetup: https://docs.google.com/presentation/d/1IWAFAVP95teMU8tZCSP2jrjL3dHlfrDjuDNuE07RAGM/edit#slide=id.g309c0578bd_0_75

**Comment by taylor** [comment]
recording https://www.youtube.com/watch?v=BR0Lzt8VN5k
