### ISSUE TITLE
Topic Ideas: book review the alliance by Reid Hoffman

### ISSUE THREAD

**Issue by williscool** [vulk/Austin_Software_Co-operatives#31]
I think you might like this book – "The Alliance: Managing Talent in the Networked Age" by Reid Hoffman, Ben Casnocha, Chris Yeh.

References:
- http://www.theallianceframework.com/
- https://www.goodreads.com/book/show/20763746-the-alliance
- available free
   - http://www.theallianceframework.com/uploads/7/8/2/9/7829688/the-alliance_chapter.pdf
   - amazon kindle: https://a.co/bKGHShU
   - audible: https://www.audible.com/pd/The-Alliance-Audiobook/B00LFS7MFM

**Comment by taylor** [comment]
Slides: https://docs.google.com/presentation/d/1mWxVjEnRab2mkBxxZBRnPN4Ckx7GjlTOMS0yk01cU90/edit#slide=id.gbaf39396d3_2_0
