### ISSUE TITLE
Working in Public: The Making and Maintenance of Open Source Software

### ISSUE THREAD

**Issue by taylor** [vulk/Austin_Software_Co-operatives#33]
![image](https://user-images.githubusercontent.com/26697/106837468-2646cd80-6660-11eb-82dc-00d616833d44.png)

Ref:
- https://www.goodreads.com/book/show/54140556-working-in-public
- https://www.amazon.com/dp/B08KWR85F8/

**Comment by taylor** [comment]
Reference videos
- [Nadia Eghbal presentation of The Making and Maintenance of Open Source Infrastructure to the Long Now Foundation](https://www.youtube.com/watch?v=5wLKnN3To-k) from Dec 3, 2020
- [LeadDev interview with Nadia Eghbal](https://www.youtube.com/watch?v=Ti43VK1MBM8) from Nov 4, 2020
- [Fireside with Nadia Eghbal](https://youtu.be/8X89YdZMyrQ) from Aug 2020 
- [Rebuilding the Cathedral by NAdia Eghbal](https://youtu.be/5Vy5s9p5A0M)from Jun 26, 2019

**Comment by lixuna** [comment]
Completed in March 2021

Meetup: https://www.meetup.com/Austin-Software-Co-operatives/events/gzxfglyccfbfb/

Slides: https://docs.google.com/presentation/d/17Lf0-fbdCJYf3yZ4i7-Km2ZV5D8baEjXF5PVHN2Rm-w/edit

Recording: https://www.youtube.com/watch?v=K--p_7OESB8&t=32s
