### ISSUE TITLE
[Topic idea] Part 2: The Democratic Worker-Owned Firm - David Ellerman (May 2021 meetup)

### ISSUE THREAD

**Issue by taylor** [vulk/Austin_Software_Co-operatives#39]
Continue discussion of the book The Democratic Worker-Owned Firm by David Ellerman

See https://github.com/vulk/Austin_Software_Co-operatives/issues/29 for part 1

Requested in feedback in the meetup

**Comment by taylor** [comment]
mindmap https://www.mindomo.com/mindmap/the-democratic-worker-owned-firm-663c8429e2dc48e286be501da428f593

**Comment by lixuna** [comment]
Completed in May 2021 

Meetup: https://www.meetup.com/Austin-Software-Co-operatives/events/gzxfglycchbhb/

Slides: https://docs.google.com/presentation/d/1Fj13bn4ioGBbH3NQvbLK5w1c2qBh8-uyYM-RzSTp7Ao/edit#slide=id.g309c0578bd_0_57

Recording: https://www.youtube.com/watch?v=722HS-x3tvY&t=4s
