### ISSUE TITLE
Distributed Justice with Michael Sandel

### ISSUE THREAD

**Issue by taylor** [vulk/Austin_Software_Co-operatives#48]
Applying different ethical frameworks for seeking distributed fair outcomes within a group.

Ref:
- Book: [Justice by Michael Sandel](https://www.goodreads.com/book/show/6452731-justice)

Meetup: 
- August, 2021 - https://www.meetup.com/Austin-Software-Co-operatives/events/gzxfglycclbgb/

**Comment by taylor** [comment]
Meetup https://www.meetup.com/Austin-Software-Co-operatives/events/gzxfglycclbgb/

**Comment by lixuna** [comment]
Completed in August 

Slides https://docs.google.com/presentation/d/1aUi3xAlK7XWipPiNJb1CKOtM0VYkM3tbF3AYG_MklSY/edit

Recording TBD: https://www.youtube.com/channel/UCXyz6WTwjZnK5XdKduXFDyg
