### ISSUE TITLE
[Book Review] Jackson Rising Part 2: People’s Assemblies

### ISSUE THREAD

**Issue by taylor** [vulk/Austin_Software_Co-operatives#51]

**Comment by taylor** [comment]
People’s Assembly Model

- https://jacksonrising.pressbooks.com/chapter/peoples-assembly-overview-the-jackson-peoples-assembly-model/ 
- https://jacksonrising.pressbooks.com/chapter/the-city-as-liberated-zone-the-promise-of-jacksons-peoples-assemblies/

**Comment by lixuna** [comment]
https://jxnpeoplesassembly.org/about/

**Comment by taylor** [comment]
Part 1 is in #37

**Comment by lixuna** [comment]
Completed in July 2021 

Event https://www.meetup.com/Austin-Software-Co-operatives/events/gzxfglycckbkb/

Slides https://docs.google.com/presentation/d/1O4SL2YV6BQ9gHrkvKs6JG7N3jbBeTRtZDfO4DqtTSX8/edit

Recording https://www.youtube.com/watch?v=2JKVm1ckNK8&t=3s
