### ISSUE TITLE
Review of https://coopcloud.tech/

### ISSUE THREAD

**Issue by wavell** [vulk/Austin_Software_Co-operatives#61]
Review of https://coopcloud.tech/ and interview with coopcloud provider autonomic.

March 2, 2022 with Trav at autonomic

**Comment by lixuna** [comment]
Autonomic is a worker‑owned co‑operative, dedicated to using technology to empower people making a positive difference in the world. We offer service hosting using Co‑op Cloud and other platforms, custom development, and infrastructure set‑up.

https://autonomic.zone/

**Comment by lixuna** [comment]
[Public interest](https://public-interest-tech.com/) infrastructure.

An alternative to corporate clouds built by [tech co-ops](https://www.coops.tech/manifesto).

WHAT IS CO-OP CLOUD?

Co-op Cloud is a software stack that aims to make hosting libre software applications simple for small service providers such as tech co-operatives who are looking to standardise around an open, transparent and scalable infrastructure. It uses the latest container technologies and configurations are shared into the commons for the benefit of all.

**Comment by lixuna** [comment]
[Trav Fryer](http://teafry.me/) is an independent artist, worker/owner at the technology cooperative [Autonomic](https://autonomic.zone/), board member of [Laboratory B](https://www.laboratoryb.org/) cooperative hackerspace, co-founder of [Burlington Federation of Cooperative Houses](http://coopfed.party/) and secretary of the board of the [Vermont Real Estate Cooperative](http://vrec.coop/).

**Comment by lixuna** [comment]
Completed on March 2nd 

Slides https://docs.google.com/presentation/d/1MRGAZV_O5W7seswiG4vVBi_ssh85qNifRZYq4inAwhs/edit#slide=id.p
