### ISSUE TITLE
Democracy Incorporated - Sheldon Wolin

### ISSUE THREAD

**Issue by wavell** [vulk/Austin_Software_Co-operatives#64]
Managed Democracy and the Specter of Inverted Totalitarianism

**Comment by taylor** [comment]
https://www.audible.com/pd/Democracy-Incorporated-Audiobook/B00456PPFK

**Comment by taylor** [comment]
https://www.truthdig.com/articles/sheldon-wolin-and-inverted-totalitarianism/

**Comment by lixuna** [comment]
Picked this for May 4th, 2022

**Comment by taylor** [comment]
https://www.goodreads.com/book/show/2326295.Democracy_Incorporated
