### ISSUE TITLE
No Shortcuts: Organizing for Power in the New Gilded Age - Jane F. McAlevey

### ISSUE THREAD

**Issue by wavell** [vulk/Austin_Software_Co-operatives#66]
- https://www.amazon.com/No-Shortcuts-Jane-F-McAlevey-audiobook/dp/B07YVNGFNF/
- https://www.goodreads.com/book/show/29639226-no-shortcuts

> The crisis of the progressive movement is so evident that nothing less than a fundamental rethinking of its basic assumptions is required. Today's progressives now work for professional organizations more comfortable with the inside game in Washington DC (and capitols throughout the West), where they are outmatched and outspent by corporate interests. Labor unions now focus on the narrowest possible understanding of the interests of their members, and membership continues to decline in lockstep with the narrowing of their goals. Meanwhile, promising movements like Occupy Wall Street and Black Lives Matter lack sufficient power to accomplish meaningful change. Why do progressives in the United States keep losing on so many issues?
> 
> In No Shortcuts, Jane McAlevey argues that progressives can win, but lack the organized power to enact significant change, to outlast their bosses in labor fights, and to hold elected leaders accountable. Drawing upon her experience as a scholar and longtime organizer in the student, environmental, and labor movements, McAlevey examines cases from labor unions and social movements to pinpoint the factors that helped them succeed - or fail - to accomplish their intended goals. McAlevey makes a compelling case that the great social movements of previous eras gained their power from mass organizing, a strategy today's progressives have mostly abandoned in favor of shallow mobilization or advocacy. She ultimately concludes that, in order to win, progressive movements need strong unions built from bottom-up organizing strategies that place the power for change in the hands of workers and ordinary people at the community level.
> 
> Beyond the concrete examples in this book, McAlevey's arguments have direct implications for anyone involved in organizing for social change. Much more than cogent analysis, No Shortcuts explains exactly how progressives can go about rebuilding powerful movements at work, in our communities, and at the ballot box.

**Comment by lixuna** [comment]
https://www.meetup.com/austin-software-co-operatives/events/gzxfglydckbjb/
